### ISSUE TITLE
Incompatible Arguments in main.cpp

### ISSUE THREAD

**Issue by doggycs** [gameAutomationMNNIT/Counter-Strike-Global-Offensive-Aimbot#5]
I am kinda retarded help me please.

![image](https://user-images.githubusercontent.com/33452790/50570643-894a4400-0db8-11e9-847f-bf3efb94f990.png)

**Comment by iosdev474** [comment]
@doggycs you can fix this issue either by 
- changing formal parameter from char * to const char * and LPSTR to LPCSTR
- or, turning off Conformance mode.

I am closing this issue if you need further assistance feel free to comment here.
